server:
  port: 8081

spring:
  datasource:
    username: root
    password: 82618261
    url: jdbc:mysql://localhost:3306/serverdb

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: false
